### ISSUE TITLE
Código para visualizar los datos

### ISSUE THREAD

**Issue by categulario** [codeandoxalapa/hackea-el-transporte-publico#2]
Durante el flisol vimos un pequeño demo que permitía visualizar la información de los camiones. Eso definitivamente es fundamental ya que la información está en nuestras manos. ¿Y si se sube aquí? Me encantaría poder enviar algunos PR para darle movimiento a este proyecto.

**Comment by jmbecerril** [comment]
Con gusto vamos a compartir ese demo que como bien mencionas nos permite visualizar un par de rutas del transporte público, no hay problema lo subimos :)

**Comment by jmbecerril** [comment]
Acabamos de subir el demo para visualizar un par de rutas de Transporte Público, lo único que requieres es colocar la carpeta "demo" en tu localhost para poder utilizarlo. Pensamos que también sería interesante e importante generar algunos storyboards antes de comenzar a codificar :)

**Comment by cesariux23** [comment]
como obtuvieron las imágenes de las rutas?

**Comment by categulario** [comment]
@cesariux23 en el flisol mencionaron la API de geocoding de google y otras apis que permiten obtener imágenes a partir de puntos. También los mapeadores capturaron imágenes.
